### ISSUE TITLE
Python3 support on pypi package

### ISSUE THREAD

**Issue by XayOn** [plasmashadow/pylocated#3]

**Comment by XayOn** [comment]
Pypi has a pylocated 2.0.0 package wich seems to be an old version.
Either bumping this one into a >2.0.0 version or removing the other should fix it.

**Comment by XayOn** [comment]
Pypi package pylocated 1.0.0 seems to have an old version too...

**Comment by sourcepirate** [comment]
@XayOn Kindly raise a PR with the required changes. I will merge it. 
[#4](https://github.com/sourcepirate/pylocated/issues/4)

**Comment by XayOn** [comment]
@sourcepirate Update the package on pypi please :)

python setup.py sdist upload

;-)

**Comment by sourcepirate** [comment]
@XayOn Done. Now available in pypi https://pypi.python.org/pypi/pylocated

**Comment by XayOn** [comment]
Amazing! Thanks!
