### ISSUE TITLE
Support for python 3

### ISSUE THREAD

**Issue by sourcepirate** [plasmashadow/pylocated#4]

**Comment by XayOn** [comment]
Done but it's broken in py3. I'll make another tomorrow with more changes

**Comment by sourcepirate** [comment]
Sure.

**Comment by XayOn** [comment]
py34: commands succeeded
  py35: commands succeeded
  py36: commands succeeded
  py27: commands succeeded

**Comment by XayOn** [comment]
This issue can be fixed now :)
